# Dependabot configuration for automated dependency updates
version: 2

updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    
    # Security updates
    open-pull-requests-limit: 10
    
    # Grouping strategy for related updates
    groups:
      aws-dependencies:
        patterns:
          - "aws-*"
          - "@aws-*"
      
      testing-dependencies:
        patterns:
          - "jest*"
          - "@types/jest"
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      
      lambda-powertools:
        patterns:
          - "@aws-lambda-powertools/*"
    
    # Auto-merge configuration for security patches
    auto-merge:
      - dependency-type: "direct:production"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
    
    # Commit message configuration
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Pull request configuration
    reviewers:
      - "security-team"
    assignees:
      - "devops-team"
    
    # Labels for categorization
    labels:
      - "dependencies"
      - "automated"
    
    # Ignore specific dependencies that require manual review
    ignore:
      - dependency-name: "aws-sdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/New_York"
    
    open-pull-requests-limit: 5
    
    commit-message:
      prefix: "ci"
      include: "scope"
    
    labels:
      - "github-actions"
      - "ci-cd"
      - "automated"
    
    reviewers:
      - "devops-team"

  # Enable version updates for Docker (if using containerized builds)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/New_York"
    
    open-pull-requests-limit: 3
    
    commit-message:
      prefix: "docker"
      include: "scope"
    
    labels:
      - "docker"
      - "infrastructure"
      - "automated"