version: 0.2

# Simplified buildspec for compilation and testing only
# Use this for build-only pipelines or when deployment is handled separately

env:
  variables:
    NODE_VERSION: "18"
    PACKAGE_NAME: "lambda-function.zip"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing build tools..."
      - npm --version
      - node --version

  pre_build:
    commands:
      - echo "Installing dependencies and running tests..."
      - npm ci
      - npm run lint
      - npm test

  build:
    commands:
      - echo "Building Lambda package..."
      - chmod +x scripts/build-lambda-package.sh
      - ./scripts/build-lambda-package.sh
      
      - echo "Package built successfully:"
      - ls -la $PACKAGE_NAME
      - cat package-manifest.json

artifacts:
  files:
    - lambda-function.zip
    - package-manifest.json
    - lambda-function.zip.sha256
    - coverage/**/*
  
  name: lambda-compile-artifacts

cache:
  paths:
    - node_modules/**/*