# Checkov configuration for Lambda production readiness
# This configuration enforces security and compliance policies for IaC

# Framework configurations
framework:
  - terraform
  - cloudformation
  - serverless

# Skip checks that are not applicable to Lambda workloads
skip-check:
  - CKV_AWS_1   # EBS encryption (not applicable to Lambda)
  - CKV_AWS_3   # EBS snapshot encryption (not applicable to Lambda)
  - CKV_AWS_4   # EBS encryption by default (not applicable to Lambda)

# Enforce critical security checks
check:
  # Lambda-specific checks
  - CKV_AWS_45  # Lambda function is configured for function-level concurrent execution limit
  - CKV_AWS_50  # X-Ray tracing is enabled for Lambda function
  - CKV_AWS_115 # Lambda function is configured for a Dead Letter Queue(DLQ)
  - CKV_AWS_116 # Lambda function is configured for function-level concurrent execution limit
  - CKV_AWS_117 # Lambda function is configured to validate code-signing
  - CKV_AWS_173 # Lambda function is configured to validate code-signing

  # IAM checks
  - CKV_AWS_39  # IAM role/policy should not use '*' in Actions for services
  - CKV_AWS_40  # IAM policy should not use '*' in Resources
  - CKV_AWS_49  # IAM role/policy should not use '*' in Actions
  - CKV_AWS_60  # IAM role has an attached policy
  - CKV_AWS_61  # IAM role allows only specific services or principals to assume it
  - CKV_AWS_62  # IAM role allows only specific principals to assume it

  # API Gateway checks
  - CKV_AWS_73  # API Gateway has X-Ray Tracing enabled
  - CKV_AWS_76  # API Gateway has Access Logging configured
  - CKV_AWS_120 # API Gateway caching is enabled
  - CKV_AWS_131 # API Gateway domain name uses a security policy
  - CKV_AWS_139 # API Gateway method has request validation enabled

  # Encryption checks
  - CKV_AWS_7   # Ensure rotation for customer created CMKs is enabled
  - CKV_AWS_33  # ECR repository has image scanning configured
  - CKV_AWS_51  # ECR Image scanning is enabled

  # Logging and monitoring
  - CKV_AWS_92  # ELB access logging is enabled
  - CKV_AWS_91  # Load Balancer access logging is enabled

# Custom policies directory (if exists)
# external-checks-dir:
#   - ./custom-policies

# Baseline file for suppressing known issues (if exists)
# baseline: .checkov.baseline

# Compact output for CI/CD
compact: true

# Download external modules
download-external-modules: true