name: CloudFormation Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      action:
        description: Action
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - delete

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-Lambda-${{ github.event.inputs.environment == 'production' && 'Production' || 'Staging' }}
          aws-region: us-east-1

      - name: Deploy CloudFormation
        if: github.event.inputs.action == 'deploy'
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/template.yaml \
            --stack-name lambda-stack-${{ github.event.inputs.environment }} \
            --parameter-overrides Environment=${{ github.event.inputs.environment }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset

      - name: Delete Stack
        if: github.event.inputs.action == 'delete'
        run: |
          aws cloudformation delete-stack \
            --stack-name lambda-stack-${{ github.event.inputs.environment }}
          
          aws cloudformation wait stack-delete-complete \
            --stack-name lambda-stack-${{ github.event.inputs.environment }}