name: Test OIDC Simple

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-oidc-simple.yml'

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_STAGING }}:role/GitHubActions-Lambda-Staging
          role-session-name: GitHubActions-OIDCTest
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Test AWS credentials
        run: |
          echo "Testing AWS OIDC authentication..."
          aws sts get-caller-identity
          echo "✅ OIDC authentication successful!"